### ISSUE TITLE
Add delay and retries between external API calls 

### ISSUE THREAD

**Issue by namvdo** [rudi-cilibrasi/libqsearch-clean#70]
We have 2 major tasks for this issue, first:
* All requests to the external APIs should only use one path on the proxy server and simply just forward the request and relay back the response. 
For example, we expect to have the proxy works in this way: 
```js
const clientRequestUri = getRequestUri(URL, method, params);
const proxyService = ...;
const response = forward(clientRequestUri); 
const response = proxyService.relayResponse(clientRequest, response);
```
* For each external call, there should be some retries for each call and some random jitter. There is already a function `fetchWithRetry`, you should also make the request with some random delay. 
* Then, create tests to verify changes are correct.

**Comment by Sonnpm197** [comment]
finished adding delay, will add jitter in the next PR
